# Generated by Django 2.0.2 on 2018-03-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snailshell_cp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField()),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeployJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('image_name', models.CharField(max_length=255)),
                ('image_tag', models.CharField(max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snailshell_cp.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
