# Generated by Django 2.0.2 on 2018-03-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snailshell_cp', '0002_accesskey_deployjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeProvisionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='is_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodeprovisionjob',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snailshell_cp.Node'),
        ),
    ]
